### ISSUE TITLE
install gitkraken glo

### ISSUE THREAD

**Issue by blancmatter** [blancmatter/sdb_puller#8]
So I could add you as a collaborator to the respoitory on github,

Ok gitkraken glo though your name doesn't aoutmatically come up when assiging @username in the title of creating a card. Perhaps you need to be a member of the board that requires glo to be used rather than just github issues.

If you sign up and link to the git account then hopefully this will resolve it. https://app.gitkraken.com/glo/

**Comment by blancmatter** [comment]
So I could add you as a collaborator to the respoitory on github,

Ok gitkraken glo though your name doesn't aoutmatically come up when assiging @username in the title of creating a card. Perhaps you need to be a member of the board that requires glo to be used rather than just github issues.

If you sign up and link to the git account then hopefully this will resolve it. https://app.gitkraken.com/glo/

**Comment by blancmatter** [comment]
![image](https://app.gitkraken.com/api/glo/boards/5d015304b21c58000ff90048/attachments/5d02616bf9378c000f0ef696)

Glo does acknowledge you as a collaborator to the repository, but does nothing if I click invite to invite you to the board. so think you need a glo user credential linked to the github account to do this.

**Comment by dcopl5577** [comment]
Account created and link accepted within GitKraken
