### ISSUE TITLE
DC test issue -raising new one

### ISSUE THREAD

**Issue by dcopl5577** [blancmatter/sdb_puller#9]
- [x] Confirm assigned process worked correctly
- [x] Close out with comment

**Comment by dcopl5577** [comment]
Please confirm this task assigning correctly by commenting and closing out!

P.s. YOU CAN DRAG AND DROP ATTACHMENTS!! mega bonus for us GUI lovers :)

[Attachment test.txt](https://app.gitkraken.com/api/glo/boards/5d015304b21c58000ff90048/attachments/5d026464b21c58000ff9173f)

**Comment by blancmatter** [comment]
All seemed to work. Also I got a load of notifications of EVERY actuion that occured on the board, but was able to turn that down a bit.

@dcopley tags in the comments should also work to highpight peopl;e to certain things.

I'm not sure about how useful this will be for NRT at the moment. Certainly software development will require a system of feature and bug tracking for which this is useful, but with the NRT activities we're all working on quite seperate, unrelated elements. It WOULD be good however for LT operations and bugs.....
